version: '5'
services:
  coupling_tool:
    build: .
    expose:
      - "5001"
    volumes:
      - app-volume:/app
    environment:
      - REDIS_URL=redis://redis:6379/0

#  flaskapp2:
#    build: .
#    expose:
#      - "5001"
#    volumes:
#      - app-volume:/app
#    environment:
#      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A coupling.celery_worker.celery worker --loglevel=info
    volumes:
      - app-volume:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - coupling_tool
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "5985:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - coupling_tool
      - redis

volumes:
  app-volume:
